# Generated by Django 5.0.6 on 2024-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immeuble_app', '0002_formulairecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireListeDesProprietaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom')),
                ('aptNum', models.IntegerField(blank=True, null=True, verbose_name='Nº Apt')),
                ('tel', models.CharField(max_length=120, verbose_name='Tel')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('proprietaire_locataire', models.CharField(choices=[('Proprietaire', 'Proprietaire'), ('Locataire', 'Locataire')], max_length=120, verbose_name='Proprietaire/Locataire')),
            ],
        ),
    ]
