# Generated by Django 5.0.6 on 2024-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immeuble_app', '0004_formulairecotization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairecotization',
            name='frais_sindic',
            field=models.CharField(blank=True, choices=[('', '----'), ('Frais Sindic', 'Frais Sindic')], max_length=120, verbose_name='Frais Sindic'),
        ),
    ]
