# Generated by Django 5.0.6 on 2024-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immeuble_app', '0005_alter_formulairecotization_frais_sindic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairecotization',
            name='frais_sindic',
            field=models.CharField(blank=True, max_length=120, verbose_name='Frais Sindic'),
        ),
    ]
