# Generated by Django 5.0.6 on 2024-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immeuble_app', '0009_formulairecotization_frais_sindic_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairecotization',
            name='cod_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code ID'),
        ),
    ]
