# Generated by Django 5.0.6 on 2024-08-04 11:47

import gestion_immeuble_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immeuble_app', '0013_alter_formulairecharge_image_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairecotization',
            name='image_signer',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[gestion_immeuble_app.models.validate_file_extension], verbose_name='Document Signé'),
        ),
    ]
